Update Privacy Policy to 4.2.0
cyface-de/ios-backend pull request #115
Opened 2021-04-08 12:29 UTC by muthenberg

Sans Sentry

2021-04-08 12:45 UTC, hb0 requested changes
Siehe Änderungsvorschlag.

Ansonsten noch: Siehe Confluence-Seite:

```
App Stores
- Google Play Store (4.2.0)
- iOS App Store (3.0.0)
```

Ist das noch so aktuell? Oder musst du keine DSE im App Store hinterlegen? Dann bitte das anstatt von `3.0.0` dort protokollieren. Danke!

2021-04-08 12:45 UTC, hb0 commented on Example/Source/ViewController/PrivacyPolicyViewController.swift
> +    public static let currentPrivacyPolicyVersion = 2
Bei Android verwende ich da die "API" Stelle der Datenschutz-Version, also bei "4.2.0" z.B. "4".

Ich denke es wäre hier sinnvoll, wenn du das bei iOS ähnlich machen würdest, also hier einmalig auf 4 hochsetzen.

Ich achte bei der Versionierung darauf, dass ich die erste Stelle der Version immer dann heraufsetze, wenn der Nutzer erneut zustimmen muss.

2021-04-08 12:53 UTC, muthenberg commented on Example/Source/ViewController/PrivacyPolicyViewController.swift
> +    public static let currentPrivacyPolicyVersion = 2
Wieso muss der Nutzer nur bei Änderungen an erster Stelle neu zustimmen? eigentlich muss er doch bei jeder Änderung zustimmen.

2021-04-08 13:11 UTC, hb0 commented on Example/Source/ViewController/PrivacyPolicyViewController.swift
> +    public static let currentPrivacyPolicyVersion = 2
Siehe Confluence Seite, ich hatte die Versionierung bisher so gehandhabt:

- Letzte Stelle -> Formatierung geändert
- 2. Stelle -> Änderung die keine Zustimmung braucht, z.B. wenn wir unsere Telefonnummer aktualisieren.
- 1. Stelle -> Nutzer muss erneut zustimmen.

Es würde aber auch Sinn machen, jedes Mal um eine Zustimmung zu bitten, auch wenn ein Typo oder die Formatierung geändert wurde. Dann sollten wir aber mittelfristig dem Nutzer sagen, was sich geändert hat, ansonsten wäre das aus Nutzersicht sehr unangenehm, wenn er die ganzen Bestimmungen erneut lesen/überfliegen muss.

2021-04-22 07:59 UTC, muthenberg commented
> Siehe Änderungsvorschlag.
> 
> Ansonsten noch: Siehe Confluence-Seite:
> 
> ```
> App Stores
> - Google Play Store (4.2.0)
> - iOS App Store (3.0.0)
> ```
> 
> Ist das noch so aktuell? Oder musst du keine DSE im App Store hinterlegen? Dann bitte das anstatt von `3.0.0` dort protokollieren. Danke!

Ich kann nur eine URL zu der Datenschutzerklärung hinterlegen. Zur Zeit zeigt diese auf unsere Webseite. Wahrscheinlich wäre es besser hier eine Seite mit der wirklichen Erklärung zu erstellen.

2021-04-22 13:03 UTC, muthenberg commented
> > Siehe Änderungsvorschlag.
> > Ansonsten noch: Siehe Confluence-Seite:
> > ```
> > App Stores
> > - Google Play Store (4.2.0)
> > - iOS App Store (3.0.0)
> > ```
> > 
> > 
> > Ist das noch so aktuell? Oder musst du keine DSE im App Store hinterlegen? Dann bitte das anstatt von `3.0.0` dort protokollieren. Danke!
> 
> Ich kann nur eine URL zu der Datenschutzerklärung hinterlegen. Zur Zeit zeigt diese auf unsere Webseite. Wahrscheinlich wäre es besser hier eine Seite mit der wirklichen Erklärung zu erstellen.

So. Die Verknüpfung ist hinzugefügt. Das kommt dann mit dem nächsten Release der App.

2021-04-22 13:25 UTC, hb0 submitted a review, later dismissed

2021-04-22 14:50 UTC, hb0 approved these changes

2021-04-22 15:29 UTC, merged